### ISSUE TITLE
[BUG] Broken eAIP link for country

### ISSUE THREAD

**Issue by BrakingChanges** [VATSIM-SSA/sectorfile-hkna#26]
**Describe the Bug**
Broken link

**To Reproduce**

1. Go to README
2. Scroll down to eAIP link

**Expected Behavior**
Redirecting to the eAIP

**Screenshots**

**Additional Context**

**Comment by miguellords** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
